// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY6ji2izKyEw3O2VrTsECjEGKhBKZG0Rg',
    appId: '1:533300417482:web:e2c23aed084837598db533',
    messagingSenderId: '533300417482',
    projectId: 'fir-tutorial-b1947',
    authDomain: 'fir-tutorial-b1947.firebaseapp.com',
    storageBucket: 'fir-tutorial-b1947.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPZkqcfImllG33Q90Q2949N1xbA8-DzG0',
    appId: '1:533300417482:android:2e1587d962ed29638db533',
    messagingSenderId: '533300417482',
    projectId: 'fir-tutorial-b1947',
    storageBucket: 'fir-tutorial-b1947.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR6jbffNcErCPFwHrhBaOuvyKLznsThrg',
    appId: '1:533300417482:ios:e7af49478cbd05e48db533',
    messagingSenderId: '533300417482',
    projectId: 'fir-tutorial-b1947',
    storageBucket: 'fir-tutorial-b1947.firebasestorage.app',
    iosBundleId: 'com.example.mentalHeatlhApp',
  );
}
